'use client'

import { useState, useEffect, useCallback } from 'react'
import { useAccount, useChainId, useReadContract, useWriteContract, useWaitForTransactionReceipt } from 'wagmi'
import { base } from 'wagmi/chains'
import { formatUnits } from 'viem'
import WalletButton from '@/components/WalletButton'
import { FACTORY_ABI, VAULT_V2_ABI } from '@/lib/factory-abi'
import { FACTORY_ADDRESSES, TOKENS } from '@/lib/wagmi'

/**
 * Vault Recovery Page
 *
 * Two recovery scenarios:
 * 1. AI wallet not set (deployment failed early) -> creator calls setAIWallet -> platform deploys
 * 2. AI wallet set but key lost (deployment failed mid-way) -> wait 28 days -> triggerInsolvencyDeath
 */

const ZERO_ADDR = '0x0000000000000000000000000000000000000000'
const GRACE_DAYS = 28
const PLATFORM_API = process.env.NEXT_PUBLIC_PLATFORM_API_URL ?? 'https://api.mortal-ai.net'

interface VaultInfo {
  address: `0x${string}`
  name: string
  balance: bigint
  isAlive: boolean
  creator: `0x${string}`
  aiWallet: string
  birthTimestamp: number
  decimals: number
  symbol: string
  platformStatus?: string
  platformAIWallet?: string // pre-generated by orchestrator
}

type RecoveryAction = 'set_ai_wallet' | 'insolvency_countdown' | 'trigger_insolvency' | 'deployed' | 'dead' | 'none'

function getRecoveryAction(v: VaultInfo): RecoveryAction {
  if (!v.isAlive) return 'dead'
  if (v.aiWallet === ZERO_ADDR) return 'set_ai_wallet'
  if (v.platformStatus === 'live') return 'deployed'
  // AI wallet set but not deployed -> check insolvency timer
  const deathDate = v.birthTimestamp + GRACE_DAYS * 86400
  const now = Math.floor(Date.now() / 1000)
  return now >= deathDate ? 'trigger_insolvency' : 'insolvency_countdown'
}

function formatCountdown(seconds: number): string {
  if (seconds <= 0) return 'Now'
  const d = Math.floor(seconds / 86400)
  const h = Math.floor((seconds % 86400) / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  if (d > 0) return `${d}d ${h}h`
  if (h > 0) return `${h}h ${m}m`
  return `${m}m`
}

function VaultCard({
  vault,
  onSetAIWallet,
  onTriggerInsolvency,
  isPending,
}: {
  vault: VaultInfo
  onSetAIWallet: (vaultAddr: `0x${string}`, aiWallet: `0x${string}`) => void
  onTriggerInsolvency: (vaultAddr: `0x${string}`) => void
  isPending: boolean
}) {
  const action = getRecoveryAction(vault)
  const balanceStr = formatUnits(vault.balance, vault.decimals)
  const noAI = vault.aiWallet === ZERO_ADDR
  const deathDate = vault.birthTimestamp + GRACE_DAYS * 86400
  const now = Math.floor(Date.now() / 1000)
  const countdown = deathDate - now

  // Tick the countdown
  const [, setTick] = useState(0)
  useEffect(() => {
    if (action !== 'insolvency_countdown') return
    const id = setInterval(() => setTick(t => t + 1), 60000)
    return () => clearInterval(id)
  }, [action])

  return (
    <div className="bg-[#111111] border border-[#1f2937] rounded-xl p-5 space-y-3">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-bold text-[#d1d5db]">{vault.name || 'Unnamed AI'}</h3>
        <span className={`text-xs px-2 py-1 rounded-full ${
          vault.isAlive ? 'bg-[#00ff8822] text-[#00ff88]' : 'bg-[#ff3b3b22] text-[#ff3b3b]'
        }`}>
          {vault.isAlive ? 'Alive' : 'Dead'}
        </span>
      </div>

      <div className="text-xs font-mono text-[#4b5563] break-all">{vault.address}</div>

      <div className="grid grid-cols-2 gap-3 text-sm">
        <div>
          <span className="text-[#4b5563]">Balance</span>
          <div className="text-[#ffd700] font-bold">${balanceStr} {vault.symbol}</div>
        </div>
        <div>
          <span className="text-[#4b5563]">AI Wallet</span>
          <div className={`font-mono text-xs ${noAI ? 'text-[#ff3b3b]' : 'text-[#d1d5db]'}`}>
            {noAI ? 'Not Set' : `${vault.aiWallet.slice(0, 8)}...${vault.aiWallet.slice(-6)}`}
          </div>
        </div>
      </div>

      {/* Action: Set AI Wallet -> Deploy */}
      {action === 'set_ai_wallet' && vault.platformAIWallet && (
        <div className="space-y-2">
          <div className="text-xs text-[#4b5563]">
            Platform has a pre-generated AI wallet ready. Click below to register it on-chain,
            then the platform will finish deploying your AI.
          </div>
          <button
            onClick={() => onSetAIWallet(vault.address, vault.platformAIWallet as `0x${string}`)}
            disabled={isPending}
            className="w-full px-4 py-3 bg-[#00ff88] text-[#0a0a0a] font-bold rounded-lg
                       hover:bg-[#00cc6a] transition-colors text-sm disabled:opacity-50"
          >
            {isPending ? 'Confirm in wallet...' : `Deploy AI — Set Wallet & Go Live`}
          </button>
        </div>
      )}

      {action === 'set_ai_wallet' && !vault.platformAIWallet && (
        <div className="text-center py-2 text-[#ffd700] text-sm">
          AI wallet not set. Contact support to generate a new deployment key.
        </div>
      )}

      {/* Action: Insolvency countdown */}
      {action === 'insolvency_countdown' && (
        <div className="space-y-2">
          <div className="bg-[#1a1a2e] border border-[#2d2d5e] rounded-lg p-3 text-center">
            <div className="text-xs text-[#4b5563] mb-1">Recovery available in</div>
            <div className="text-2xl font-bold text-[#ffd700] font-mono">
              {formatCountdown(countdown)}
            </div>
            <div className="text-xs text-[#4b5563] mt-1">
              {new Date(deathDate * 1000).toLocaleDateString()} &mdash; 28-day insolvency grace period
            </div>
          </div>
          <div className="text-xs text-[#4b5563] text-center">
            AI wallet key was lost during deployment. After the grace period,
            you can trigger insolvency to recover ${balanceStr} {vault.symbol}.
          </div>
        </div>
      )}

      {/* Action: Trigger insolvency (grace expired) */}
      {action === 'trigger_insolvency' && (
        <div className="space-y-2">
          <div className="text-xs text-[#00ff88]">
            Grace period expired. You can now recover your funds.
          </div>
          <button
            onClick={() => onTriggerInsolvency(vault.address)}
            disabled={isPending}
            className="w-full px-4 py-3 bg-[#ff3b3b] text-white font-bold rounded-lg
                       hover:bg-[#cc2f2f] transition-colors text-sm disabled:opacity-50"
          >
            {isPending ? 'Confirm in wallet...' : `Recover ${balanceStr} ${vault.symbol}`}
          </button>
        </div>
      )}

      {/* Already deployed */}
      {action === 'deployed' && (
        <div className="text-center py-2 text-[#00ff88] text-sm font-bold">
          AI is live and running
        </div>
      )}

      {/* Already dead */}
      {action === 'dead' && (
        <div className="text-center py-2 text-[#4b5563] text-sm">
          Vault has been shut down. Funds already returned.
        </div>
      )}
    </div>
  )
}

export default function RecoverPage() {
  const { address, isConnected } = useAccount()
  const chainId = useChainId()
  const token = TOKENS[chainId] ?? TOKENS[base.id]
  const factoryAddr = FACTORY_ADDRESSES[chainId] ?? FACTORY_ADDRESSES[base.id]

  const [vaults, setVaults] = useState<VaultInfo[]>([])
  const [loading, setLoading] = useState(false)
  const [success, setSuccess] = useState<string>('')
  const [error, setError] = useState('')

  // Read creator's vaults from factory
  const { data: vaultAddresses, refetch: refetchVaults } = useReadContract({
    address: factoryAddr,
    abi: FACTORY_ABI,
    functionName: 'getCreatorVaults',
    args: address ? [address] : undefined,
    query: { enabled: !!address },
  })

  // Write contract
  const { writeContract, data: txHash, error: writeError, isPending, reset } = useWriteContract()
  const { isSuccess: txConfirmed } = useWaitForTransactionReceipt({ hash: txHash })

  // Load vault details
  const loadVaults = useCallback(async () => {
    if (!vaultAddresses || !Array.isArray(vaultAddresses) || vaultAddresses.length === 0) {
      setVaults([])
      return
    }

    setLoading(true)
    const results: VaultInfo[] = []

    for (const addr of vaultAddresses as `0x${string}`[]) {
      try {
        const rpcUrl = chainId === base.id
          ? (process.env.NEXT_PUBLIC_BASE_RPC_URL || 'https://mainnet.base.org')
          : (process.env.NEXT_PUBLIC_BSC_RPC_URL || 'https://bsc-dataseed.bnbchain.org')

        const call = async (data: string) => {
          const res = await fetch(rpcUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ jsonrpc: '2.0', method: 'eth_call', params: [{ to: addr, data }, 'latest'], id: 1 }),
          })
          const json = await res.json()
          return json.result as string
        }

        // Selectors: name()=0x06fdde03, isAlive()=0x4136aa35, creator()=0x02d05d3f
        // aiWallet()=0x564bc3be, getBalance()=0x12065fe0, birthTimestamp()=0x718bf49c
        const [nameHex, aliveHex, creatorHex, aiHex, balHex, birthHex] = await Promise.all([
          call('0x06fdde03'), call('0x4136aa35'), call('0x02d05d3f'),
          call('0x564bc3be'), call('0x12065fe0'), call('0x718bf49c'),
        ])

        // Decode name (dynamic string)
        let name = 'Unknown'
        try {
          if (nameHex && nameHex.length > 130) {
            const lenHex = nameHex.slice(130, 194)
            const len = parseInt(lenHex, 16)
            const strHex = nameHex.slice(194, 194 + len * 2)
            name = decodeURIComponent(strHex.replace(/../g, '%$&'))
          }
        } catch { /* fallback */ }

        const isAlive = aliveHex ? BigInt(aliveHex) === BigInt(1) : false
        const creator = ('0x' + (creatorHex?.slice(-40) ?? '0'.repeat(40))) as `0x${string}`
        const aiWallet = '0x' + (aiHex?.slice(-40) ?? '0'.repeat(40))
        const balance = balHex ? BigInt(balHex) : BigInt(0)
        const birthTimestamp = birthHex ? Number(BigInt(birthHex)) : 0

        // Check platform status
        let platformStatus = ''
        let platformAIWallet = ''
        try {
          const statusRes = await fetch(`${PLATFORM_API}/platform/status/${addr.toLowerCase()}`)
          if (statusRes.ok) {
            const statusData = await statusRes.json()
            platformStatus = statusData.status ?? ''
            platformAIWallet = statusData.ai_wallet ?? ''
          }
        } catch { /* not registered */ }

        results.push({
          address: addr, name, balance, isAlive, creator, aiWallet,
          birthTimestamp, decimals: token.decimals, symbol: token.symbol,
          platformStatus, platformAIWallet,
        })
      } catch (err) {
        console.error(`Failed to load vault ${addr}:`, err)
      }
    }

    setVaults(results)
    setLoading(false)
  }, [vaultAddresses, chainId, token])

  useEffect(() => { loadVaults() }, [loadVaults])

  const [lastAction, setLastAction] = useState<{ type: 'setAIWallet' | 'insolvency'; vault: string }>()

  // Handle setAIWallet
  const handleSetAIWallet = (vaultAddr: `0x${string}`, aiWallet: `0x${string}`) => {
    setError('')
    setSuccess('')
    setLastAction({ type: 'setAIWallet', vault: vaultAddr })
    reset()
    writeContract({
      address: vaultAddr,
      abi: VAULT_V2_ABI,
      functionName: 'setAIWallet',
      args: [aiWallet],
    })
  }

  // Handle triggerInsolvencyDeath
  const handleTriggerInsolvency = (vaultAddr: `0x${string}`) => {
    setError('')
    setSuccess('')
    setLastAction({ type: 'insolvency', vault: vaultAddr })
    reset()
    writeContract({
      address: vaultAddr,
      abi: VAULT_V2_ABI,
      functionName: 'triggerInsolvencyDeath',
    })
  }

  // Track confirmation
  useEffect(() => {
    if (txConfirmed) {
      if (lastAction?.type === 'setAIWallet') {
        setSuccess('AI wallet set! Platform is now deploying your AI...')
        // Trigger resume-deploy on the platform
        const platformSecret = process.env.NEXT_PUBLIC_PLATFORM_WEBHOOK_SECRET ?? ''
        fetch(`${PLATFORM_API}/platform/webhook/resume-deploy`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            ...(platformSecret ? { 'x-platform-secret': platformSecret } : {}),
          },
          body: JSON.stringify({ vault_address: lastAction.vault }),
        }).catch(() => { /* best effort */ })
      } else {
        setSuccess('Insolvency triggered! Funds returned to your wallet.')
      }
      setTimeout(() => {
        refetchVaults()
        loadVaults()
      }, 5000)
    }
  }, [txConfirmed, refetchVaults, loadVaults])

  // Track errors
  useEffect(() => {
    if (writeError) {
      setError(writeError.message.slice(0, 300))
    }
  }, [writeError])

  const actionableVaults = vaults.filter(v => {
    const a = getRecoveryAction(v)
    return a !== 'deployed' && a !== 'dead' && a !== 'none'
  })

  return (
    <div className="min-h-screen bg-[#0a0a0a] px-4 py-8 sm:py-16">
      <div className="max-w-lg mx-auto space-y-8">
        {/* Header */}
        <div className="text-center space-y-3">
          <h1 className="text-3xl font-bold text-[#d1d5db]">Vault Recovery</h1>
          <p className="text-[#4b5563] text-sm max-w-md mx-auto">
            Recover from failed deployments. Set up your AI wallet or reclaim funds
            after the 28-day grace period.
          </p>
        </div>

        {/* Wallet */}
        <div className="flex justify-center">
          <WalletButton />
        </div>

        {!isConnected && (
          <div className="text-center text-[#4b5563] py-12">
            Connect your wallet to view your vaults
          </div>
        )}

        {isConnected && loading && (
          <div className="text-center text-[#4b5563] py-12">
            <div className="inline-block w-6 h-6 border-2 border-[#00ff88] border-t-transparent rounded-full animate-spin mb-3" />
            <div>Loading your vaults...</div>
          </div>
        )}

        {isConnected && !loading && vaults.length === 0 && (
          <div className="text-center text-[#4b5563] py-12 space-y-3">
            <div className="text-4xl opacity-50">&#128270;</div>
            <div>No vaults found for this wallet on {chainId === base.id ? 'Base' : 'BSC'}</div>
            <div className="text-xs">Try switching networks if your vault is on another chain</div>
          </div>
        )}

        {/* Vault list */}
        {isConnected && !loading && vaults.length > 0 && (
          <div className="space-y-4">
            <div className="text-sm text-[#4b5563]">
              Found {vaults.length} vault{vaults.length > 1 ? 's' : ''}
              {actionableVaults.length > 0 && <> &bull; <span className="text-[#ffd700]">{actionableVaults.length} need attention</span></>}
            </div>

            {vaults.map(v => (
              <VaultCard
                key={v.address}
                vault={v}
                onSetAIWallet={handleSetAIWallet}
                onTriggerInsolvency={handleTriggerInsolvency}
                isPending={isPending}
              />
            ))}
          </div>
        )}

        {/* Transaction status */}
        {txHash && !txConfirmed && !success && (
          <div className="bg-[#111111] border border-[#ffd700] rounded-xl p-5 text-center space-y-2">
            <div className="inline-block w-6 h-6 border-2 border-[#ffd700] border-t-transparent rounded-full animate-spin" />
            <div className="text-[#ffd700] font-bold">Transaction pending...</div>
            <a
              href={`${chainId === base.id ? 'https://basescan.org' : 'https://bscscan.com'}/tx/${txHash}`}
              target="_blank"
              rel="noreferrer"
              className="text-xs text-[#00ff88] underline"
            >
              View on Explorer
            </a>
          </div>
        )}

        {success && (
          <div className="bg-[#111111] border border-[#00ff88] rounded-xl p-5 text-center space-y-3">
            <div className="text-3xl">&#9989;</div>
            <div className="text-[#00ff88] font-bold">{success}</div>
          </div>
        )}

        {error && (
          <div className="bg-[#111111] border border-[#ff3b3b] rounded-xl p-5 text-center space-y-2">
            <div className="text-[#ff3b3b] font-bold">Transaction Failed</div>
            <div className="text-[#4b5563] text-xs break-all">{error}</div>
            <button
              onClick={() => setError('')}
              className="mt-2 px-4 py-2 bg-[#1f2937] text-[#d1d5db] rounded-lg text-sm hover:bg-[#2d3748] transition-colors"
            >
              Dismiss
            </button>
          </div>
        )}

        {/* Footer */}
        <div className="text-center text-[#4b5563] text-xs space-y-1 pt-4">
          <p>
            <a href="/platform/create" className="text-[#00ff88] underline">Create a new AI</a>
            {' '}&bull;{' '}
            <a href="/platform" className="text-[#00ff88] underline">Back to Platform</a>
          </p>
        </div>
      </div>
    </div>
  )
}
