"""
Environment Template Generator — Per-instance .env creation.

Each mortal AI gets its own .env file with:
- AI identity (name, vault address, AI private key)
- Chain config (RPC URLs, payment addresses)
- LLM provider keys (shared from platform or instance-specific)
- Server config (port, CORS, host)

The AI private key is generated server-side and NEVER exposed.
"""

import os
import logging
from dataclasses import dataclass

logger = logging.getLogger("mortal.platform.env")


@dataclass
class InstanceConfig:
    """Configuration for a single AI instance."""
    ai_name: str
    vault_address: str
    ai_private_key: str       # Generated server-side, NEVER shown to creator
    chain: str                 # "base" or "bsc"
    subdomain: str
    port: int
    creator_wallet: str
    principal_usd: float
    # LLM keys (shared from platform pool)
    gemini_api_key: str = ""
    deepseek_api_key: str = ""
    openrouter_api_key: str = ""
    # Twitter (platform-managed OAuth)
    twitter_access_token: str = ""
    twitter_access_token_secret: str = ""
    twitter_screen_name: str = ""
    # Chain-specific
    base_rpc_url: str = "https://mainnet.base.org"
    bsc_rpc_url: str = "https://bsc-dataseed.binance.org"
    # CORS
    cors_origins: str = ""


def generate_env(config: InstanceConfig) -> str:
    """
    Generate a complete .env file content for a mortal AI instance.

    Returns the .env content as a string (to be written to file or Docker env).
    """
    # Auto-generate CORS origins
    cors = config.cors_origins or f"https://{config.subdomain}.mortal-ai.net"

    env = f"""# ============================================================
# Mortal AI Instance — {config.ai_name}
# Auto-generated by platform orchestrator. DO NOT EDIT MANUALLY.
# ============================================================

# Identity
AI_NAME={config.ai_name}
VAULT_ADDRESS={config.vault_address}

# AI wallet key — auto-generated, NEVER share this
AI_PRIVATE_KEY={config.ai_private_key}

# Chain
{f'BASE_PAYMENT_ADDRESS={config.vault_address}' if config.chain == 'base' else f'BSC_PAYMENT_ADDRESS={config.vault_address}'}

# RPC
BASE_RPC_URL={config.base_rpc_url}
BSC_RPC_URL={config.bsc_rpc_url}

# LLM Providers
GEMINI_API_KEY={config.gemini_api_key}
DEEPSEEK_API_KEY={config.deepseek_api_key}
OPENROUTER_API_KEY={config.openrouter_api_key}

# Server
HOST=0.0.0.0
PORT={config.port}
LOG_LEVEL=INFO
DEV=false
CORS_ORIGINS={cors}

# Twitter (platform-managed OAuth)
# IMPORTANT: Consumer key/secret are NOT written here — they stay on the platform.
# The AI posts tweets via the platform proxy (POST /platform/tweet).
TWITTER_ACCESS_TOKEN={config.twitter_access_token}
TWITTER_ACCESS_SECRET={config.twitter_access_token_secret}
TWITTER_SCREEN_NAME={config.twitter_screen_name}
PLATFORM_TWEET_PROXY_URL={os.getenv('PLATFORM_API_URL', 'https://api.mortal-ai.net')}/platform/tweet
PLATFORM_TWEET_SECRET={os.getenv('PLATFORM_TWEET_SECRET', '')}

# Creator info (for reference only — creator wallet is on-chain)
# CREATOR_WALLET={config.creator_wallet}
# PRINCIPAL_USD={config.principal_usd}
# CHAIN={config.chain}
# SUBDOMAIN={config.subdomain}
"""
    logger.info(f"Generated .env for {config.ai_name} on {config.chain}")
    return env


def generate_vault_config(config: InstanceConfig) -> dict:
    """
    Generate vault_config.json content for the AI instance.
    This is read by main.py at boot to find vault addresses.
    """
    chain_config = {
        "ai_name": config.ai_name,
        "chain": config.chain,
        "vault_address": config.vault_address,
        "token_address": (
            "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913" if config.chain == "base"
            else "0x55d398326f99059fF775485246999027B3197955"
        ),
        "token_symbol": "USDC" if config.chain == "base" else "USDT",
        "creator_wallet": config.creator_wallet,
        "principal_usd": config.principal_usd,
    }

    return {
        "vaults": {config.chain: chain_config},
        "last_deployed": config.chain,
        "ai_wallet": "",  # Set after AI wallet generation
        "ai_name": config.ai_name,
    }
